services:
  transcriber:
    build:
      context: .
      dockerfile: .build/Dockerfile
    container_name: spal-transcriber
    ports:
      - "15551:15551"
    volumes:
      - ./data:/app/data
      - ./config:/app/config
      - ./.env:/app/.env:ro
